version: '2'
services:
  python-docker:
    container_name: python-docker
    build:
      context: .
      dockerfile: Dockerfile
    image: python-docker
    expose:
    - 8888
    ports:
    - 8888:8888